spring:
  liquibase:
    change-log: classpath:/config/liquibase/master.xml
  application:
      name: core-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 7002
  servlet:
    context-path: /core