spring:
  liquibase:
    change-log: classpath:/config/liquibase/master.xml
  application:
      name: auth-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8081
  servlet:
    context-path: /auth