version: "3.9"

services:
  auth-db:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: auth-db
    volumes:
      - auth-data:/var/lib/postgresql/data

  core-db:
    image: postgres:latest
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: core-db
    volumes:
      - core-data:/var/lib/postgresql/data

  mentorship-db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: mentorship-db
    ports:
      - "5434:5432"
    volumes:
      - mentorship-data:/var/lib/postgresql/data

  feedback-db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: feedback-db
    ports:
      - "5435:5432"
    volumes:
      - feedback-data:/var/lib/postgresql/data

volumes:
  auth-data:
  core-data:
  mentorship-data:
  feedback-data:
