spring:
  liquibase:
    change-log: classpath:/config/liquibase/master.xml
  application:
    name: mentorship-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 7000
  servlet:
    context-path: /mentorship