spring:
  application:
    name: notifications-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 7003
  servlet:
    context-path: /notifications