version: "3.9"

services:
  auth-db:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: auth-db
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
