spring:
  cloud:
    gateway:
      routes:
        - id: authModule
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**
            - Path=/test/**
        - id: coreModule
          uri: lb://CORE-SERVICE
          predicates:
            - Path=/core/**
        - id: mentorshipModule
          uri: lb://MENTORSHIP-SERVICE
          predicates:
            - Path=/mentorship/**
        - id: feedbackModule
          uri: lb://FEEDBACK-SERVICE
          predicates:
            - Path=/feedback/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


